"""Splice Omarchy theme colours into herdr's config.toml.

herdr mixes theme settings with the user's keybindings in one file and offers
no include mechanism, so we rewrite only what we own and leave every other byte
alone. tomlkit is not available and tomllib cannot round-trip comments, so this
is deliberately line-based rather than a parse-and-serialise.
"""

from __future__ import annotations

import re

MARK_START = "# >>> omarchy-theme >>>"
MARK_END = "# <<< omarchy-theme <<<"

# Any line that opens a new TOML table, e.g. "[ui]" or "[theme.custom]".
_SECTION = re.compile(r"^[ \t]*\[")
_ACCENT = re.compile(r"^[ \t]*accent[ \t]*=")


class SpliceError(Exception):
    """The target file is not in a shape we can safely rewrite."""


def _header(name: str) -> re.Pattern[str]:
    return re.compile(r"^[ \t]*\[" + re.escape(name) + r"\][ \t]*(#.*)?$")


def _drop_managed_block(lines: list[str]) -> list[str]:
    starts = [i for i, l in enumerate(lines) if l.strip() == MARK_START]
    ends = [i for i, l in enumerate(lines) if l.strip() == MARK_END]
    if not starts and not ends:
        return lines
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        raise SpliceError("managed block markers are missing or malformed")
    return lines[: starts[0]] + lines[ends[0] + 1 :]


def _drop_section(lines: list[str], name: str) -> list[str]:
    head = _header(name)
    out: list[str] = []
    i = 0
    while i < len(lines):
        if head.match(lines[i]):
            i += 1
            while i < len(lines) and not _SECTION.match(lines[i]):
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return out


def _set_ui_accent(lines: list[str], value: str) -> list[str]:
    """Replace `accent` inside [ui], or insert it, or create [ui] entirely."""
    head = _header("ui")
    for i, line in enumerate(lines):
        if not head.match(line):
            continue
        j = i + 1
        while j < len(lines) and not _SECTION.match(lines[j]):
            if _ACCENT.match(lines[j]):
                lines[j] = f'accent = "{value}"'
                return lines
            j += 1
        return lines[: i + 1] + [f'accent = "{value}"'] + lines[i + 1 :]
    return lines + ["", "[ui]", f'accent = "{value}"']


def splice(config_text: str, theme_block: str, ui_accent: str) -> str:
    """Return config_text with our theme sections and [ui].accent replaced.

    Everything outside the managed block and the single accent key — comments,
    blank lines, keybindings — is preserved exactly.
    """
    if not theme_block.strip():
        raise SpliceError("refusing to splice an empty theme block")

    lines = config_text.splitlines()
    lines = _drop_managed_block(lines)
    lines = _drop_section(lines, "theme.custom")
    lines = _drop_section(lines, "theme")
    lines = _set_ui_accent(lines, ui_accent)

    while lines and not lines[-1].strip():
        lines.pop()

    block = [
        "",
        MARK_START,
        "# Generated by omarchy-themed-devtools. Do not edit inside the markers.",
        *theme_block.rstrip("\n").splitlines(),
        MARK_END,
    ]
    return "\n".join(lines + block) + "\n"
