# GENERATED by omarchy-themed-devtools from the active Omarchy palette.
# Included from ~/.config/git/config; never edited by hand.
[delta]
    syntax-theme = Omarchy
    line-numbers = true
    hyperlinks = false

    minus-style                   = syntax "{{ mix background red 22% }}"
    minus-emph-style              = syntax "{{ mix background red 38% }}"
    minus-non-emph-style          = syntax "{{ mix background red 12% }}"
    plus-style                    = syntax "{{ mix background green 22% }}"
    plus-emph-style               = syntax "{{ mix background green 38% }}"
    plus-non-emph-style           = syntax "{{ mix background green 12% }}"

    file-style                    = "{{ accent }}" bold
    file-decoration-style         = "{{ mix background foreground 20% }}" ul
    hunk-header-style             = "{{ muted }}"
    hunk-header-decoration-style  = "{{ mix background foreground 20% }}" box
    hunk-header-file-style        = "{{ accent }}"
    hunk-header-line-number-style = "{{ muted }}"

    line-numbers-minus-style      = "{{ red }}"
    line-numbers-plus-style       = "{{ green }}"
    line-numbers-zero-style       = "{{ mix background foreground 30% }}"
    line-numbers-left-style       = "{{ mix background foreground 20% }}"
    line-numbers-right-style      = "{{ mix background foreground 20% }}"

    blame-palette                 = "{{ background }}" "{{ dark_background }}" "{{ lighter_background }}"
    merge-conflict-begin-symbol   = ~
    merge-conflict-end-symbol     = ~
