set -g status-style "bg={{ dark_background }},fg={{ foreground }}"
set -g status-left-style "bg={{ accent }},fg={{ background }},bold"
set -g status-right-style "bg={{ dark_background }},fg={{ muted }}"
set -g window-status-current-style "fg={{ accent }},bold"
set -g window-status-style "fg={{ muted }}"
set -g pane-border-style "fg={{ mix background foreground 20% }}"
set -g pane-active-border-style "fg={{ accent }}"
set -g message-style "bg={{ selection }},fg={{ foreground }}"
set -g mode-style "bg={{ selection }},fg={{ foreground }}"
set -g copy-mode-match-style "bg={{ accent }},fg={{ background }}"
